global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'fraud-spark-engine'
    static_configs:
      - targets: ['spark:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka:9101']
    scrape_interval: 15s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
